name: cgo-java-test

on:
  push:
    branches: [ "master", "test-java17" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 21.1.0
          native-image: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build native library
        run: mvn package

      - name: Build CGO app
        run: go build -v -o app ./example/main.go

      - name: Prepare for packagin a distributive
        run: mv ./target/libcgotest.* ./target/graal_isolate.* ./

      - name: Create a distributive
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            libcgotest.*
            graal_isolate.*
            app